language: java
jdk: oraclejdk8
branches:
  only: master
install: true
script: ".travis/build.sh"
after_success: ".travis/notify.sh Travis-Success"
after_failure: ".travis/notify.sh Travis-Failure"
env:
  global:
  - secure: Agp31hoN8YrIlWi7yf3ODFeRpaZrrlEynMF5SS/cRCMcCBz/+/9WRS4ITe2FCyp8uIM8qgq2x/WWLLPop+ynvrBda7ntVIUgpdZomapQe8S5YtoGKilPGT6BTfV7vMb83IK39EZNjgLiCosNua6yswp+oCU5kZ20r9OkGGajU4o=
  - secure: Cbr+UPSxY+tdo3tfJ7Lo2XeFE0pUZhrZX5qUs6OtALSV1Mi1MW7e8Gz+s6PJItz/bUTz5vYCs0YMqSELS+V5ilXa8da78I9tEjF04Vg75iXblVJV9gdyovmRwJwkhORY1UQAONLVPk1ckdYxw5k2+3rd4Y676ukgPhEk00/7qu4=
